services:
  portway_documentation:
    image: ghcr.io/melosso/portway_documentation:latest
    container_name: portway_documentation
    volumes:
      - ./docs:/app/docs
    ports:
      - "5991:8080"
