services:
  portway_documentation:
    image: ghcr.io/melosso/bark:latest
    container_name: portway_documentation
    ports:
      - "5991:8080"
    volumes:
      - ./docs:/app/docs
      - ./wwwroot:/app/wwwroot