using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Options;
using Microsoft.OpenApi;
using Scalar.AspNetCore;
using Serilog;

namespace PortwayApi.Classes.OpenApi;

public static class OpenApiConfiguration
{
    public static void ConfigureOpenApi(WebApplicationBuilder builder)
    {
        // Register OpenApiSettings with IOptionsMonitor for dynamic reload
        builder.Services.Configure<OpenApiSettings>(builder.Configuration.GetSection("OpenApi"));

        // Register post-configuration to apply defaults and validation
        builder.Services.PostConfigure<OpenApiSettings>(openApiSettings =>
        {
            // Ensure object references aren't null (defensive programming)
            openApiSettings.Contact ??= new ContactInfo();
            openApiSettings.Footer ??= new FooterInfo();
            openApiSettings.SecurityDefinition ??= new SecurityDefinitionInfo();

            // Validate and fix critical values
            if (string.IsNullOrWhiteSpace(openApiSettings.Title))
                openApiSettings.Title = "PortwayAPI";

            if (string.IsNullOrWhiteSpace(openApiSettings.Version))
                openApiSettings.Version = "v1";

            if (string.IsNullOrWhiteSpace(openApiSettings.SecurityDefinition.Name))
                openApiSettings.SecurityDefinition.Name = "Bearer";

            if (string.IsNullOrWhiteSpace(openApiSettings.SecurityDefinition.Scheme))
                openApiSettings.SecurityDefinition.Scheme = "Bearer";

            if (string.IsNullOrWhiteSpace(openApiSettings.ScalarTheme))
                openApiSettings.ScalarTheme = "purple";

            if (string.IsNullOrWhiteSpace(openApiSettings.ScalarLayout))
                openApiSettings.ScalarLayout = "modern";
        });

        // Get initial settings to register OpenAPI services
        var openApiSettings = new OpenApiSettings();
        var section = builder.Configuration.GetSection("OpenApi");
        if (section.Exists())
        {
            section.Bind(openApiSettings);
            Log.Debug("OpenAPI configuration loaded from appsettings.json");
        }

        // Register OpenAPI services if enabled
        if (openApiSettings.Enabled)
        {
            builder.Services.AddOpenApi(openApiSettings.Version, options =>
            {
                // Emit OpenAPI 3.2 so QUERY renders as a native query operation and namespaces as hierarchical tags
                options.OpenApiVersion = OpenApiSpecVersion.OpenApi3_2;

                // Exclude controller-discovered endpoints; all docs are generated by document transformers
                options.ShouldInclude = (description) =>
                {
                    var controller = description.ActionDescriptor.RouteValues.TryGetValue("controller", out var ctrl) ? ctrl : "Unknown";
                    var routeTemplate = description.RelativePath?.ToLowerInvariant() ?? "Unknown";

                    if (!string.IsNullOrEmpty(controller))
                    {
                        var excludedControllers = new[] { "Endpoint", "PortwayApi", "Models", "OpenApiDocs" };
                        if (excludedControllers.Contains(controller, StringComparer.OrdinalIgnoreCase))
                            return false;
                    }

                    if (!string.IsNullOrEmpty(routeTemplate))
                    {
                        var excludedRoutePatterns = new[] { "portwayapi", "models", "/models" };
                        if (excludedRoutePatterns.Any(pattern => routeTemplate.Contains(pattern)))
                            return false;
                    }

                    return true;
                };

                // Add security scheme via document transformer
                options.AddDocumentTransformer((document, context, ct) =>
                {
                    document.Components ??= new OpenApiComponents();
                    document.Components.SecuritySchemes ??= new Dictionary<string, IOpenApiSecurityScheme>();
                    var schemeType = ParseEnum<SecuritySchemeType>(openApiSettings.SecurityDefinition.Type, SecuritySchemeType.Http);
                    var scheme = new OpenApiSecurityScheme
                    {
                        Description = openApiSettings.SecurityDefinition.Description,
                        Type = schemeType
                    };

                    // name and in only apply to an apiKey scheme; an http scheme always sends its credentials in the Authorization header
                    if (schemeType == SecuritySchemeType.ApiKey)
                    {
                        scheme.Name = "Authorization";
                        scheme.In = ParseEnum<ParameterLocation>(openApiSettings.SecurityDefinition.In, ParameterLocation.Header);
                    }
                    else
                    {
                        scheme.Scheme = openApiSettings.SecurityDefinition.Scheme.ToLowerInvariant();
                    }

                    document.Components.SecuritySchemes[openApiSettings.SecurityDefinition.Name] = scheme;

                    return Task.CompletedTask;
                });

                // Add server URL transformer (replaces PreSerializeFilters)
                options.AddDocumentTransformer((document, context, ct) =>
                {
                    var httpContextAccessor = context.ApplicationServices.GetService<IHttpContextAccessor>();
                    var httpReq = httpContextAccessor?.HttpContext?.Request;
                    if (httpReq != null)
                    {
                        var currentSettings = context.ApplicationServices
                            .GetRequiredService<IOptionsMonitor<OpenApiSettings>>().CurrentValue;

                        string scheme = httpReq.Scheme;
                        bool isProduction = !string.Equals(
                            Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT"),
                            "Development", StringComparison.OrdinalIgnoreCase);
                        bool forceHttps = currentSettings.ForceHttpsInProduction && isProduction;

                        string host = httpReq.Host.HasValue ? httpReq.Host.Value : "localhost";
                        bool isLocalhost = host.Contains("localhost") || host.Contains("127.0.0.1");

                        if (forceHttps && !isLocalhost)
                            scheme = "https";

                        if (httpReq.Headers.ContainsKey("X-Forwarded-Proto") &&
                            httpReq.Headers["X-Forwarded-Proto"] == "https")
                            scheme = "https";

                        var pathBase = httpReq.PathBase.HasValue ? httpReq.PathBase.Value : "";
                        var serverUrl = $"{scheme}://{host}{pathBase}";

                        document.Servers = new List<OpenApiServer>
                        {
                            new OpenApiServer { Url = serverUrl, Name = "current", Description = "Current server" }
                        };

                        // The document's own URI, so other descriptions can reference it and relative refs resolve against it
                        if (Uri.TryCreate($"{serverUrl}/docs/openapi/{currentSettings.Version}/openapi.json", UriKind.Absolute, out var selfUri))
                        {
                            document.Self = selfUri;
                        }

                        Log.Debug("OpenAPI Server URL: {ServerUrl}", serverUrl);
                    }
                    return Task.CompletedTask;
                });

                // Add document transformers (order is critical)
                options.AddDocumentTransformer<StandardResponsesDocumentFilter>();
                options.AddDocumentTransformer<DynamicOpenApiDocumentFilter>();
                options.AddDocumentTransformer<DynamicEndpointDocumentFilter>();
                options.AddDocumentTransformer<CompositeEndpointDocumentFilter>();
                options.AddDocumentTransformer<FileEndpointDocumentFilter>();
                options.AddDocumentTransformer<SqlMetadataDocumentFilter>();
                options.AddDocumentTransformer<StaticMetadataDocumentFilter>();
                options.AddDocumentTransformer<ResponseDescriptionDocumentFilter>();
                options.AddDocumentTransformer(EndpointStateDocumentFilter.Deprecated());
                options.AddDocumentTransformer(EndpointStateDocumentFilter.Disabled());
                options.AddDocumentTransformer<TenancyDocumentFilter>();
                options.AddDocumentTransformer<TableValuedFunctionDocumentFilter>();
                options.AddDocumentTransformer<ConfigExampleDocumentFilter>();
                options.AddDocumentTransformer<GroupTitleDocumentFilter>();
                options.AddDocumentTransformer<TagSorterDocumentFilter>();

                // Apply global security requirement to all operations (runs after all endpoints are added)
                options.AddDocumentTransformer((document, context, ct) =>
                {
                    foreach (var pathItem in document.Paths.Values)
                    {
                        if (pathItem.Operations == null) continue;
                        foreach (var operation in pathItem.Operations.Values)
                        {
                            operation.Security ??= new List<OpenApiSecurityRequirement>();
                            operation.Security.Add(new OpenApiSecurityRequirement
                            {
                                [new OpenApiSecuritySchemeReference(openApiSettings.SecurityDefinition.Name, document)] = new List<string>()
                            });
                        }
                    }
                    return Task.CompletedTask;
                });

                // Add operation transformers
                options.AddOperationTransformer<DynamicEndpointOperationFilter>();
            });

            Log.Debug("OpenAPI services registered successfully");
        }
        else
        {
            Log.Information("OpenAPI documentation is disabled in configuration");
        }
    }

    public static void ConfigureDocs(WebApplication app, IOptionsMonitor<OpenApiSettings> openApiMonitor)
    {
        // Check if OpenAPI is enabled at startup
        var initialSettings = openApiMonitor.CurrentValue;
        if (!initialSettings.Enabled)
        {
            Log.Information("OpenAPI documentation is disabled in configuration");
            return;
        }

        // Configure OpenAPI JSON endpoint (server URL is handled by document transformer in ConfigureOpenApi)
        app.MapOpenApi("/docs/openapi/{documentName}/openapi.json");

        // Warn in production if unauthenticated OpenAPI docs expose endpoint topology
        if (app.Environment.IsProduction())
            Log.Warning("Unauthenticated OpenAPI specification active at '/docs'. Restrict access via proxy/network rule or set OpenApi:Enabled=false. You can dismiss this warning if you are intentionally exposing the OpenAPI spec for public consumption.");

        // Serve minimal source maps for Scalar vendor JS to prevent DevTools 404 warnings
        app.MapGet("/sm/{*path}", () => Results.Json(new { version = 3, sources = Array.Empty<string>(), mappings = "" }))
           .ExcludeFromDescription();
        // Configure unified documentation interface at /docs using Scalar
        app.MapGet("/docs", (HttpContext context) =>
        {
            // Read current configuration on each request for dynamic reload
            var openApiSettings = openApiMonitor.CurrentValue;

            // Get the base path for URL construction
            var pathBase = context.Request.PathBase.HasValue ? context.Request.PathBase.Value : "";
            var sidebarConfig = openApiSettings.ScalarShowSidebar ? "true" : "false";

            // Preselect the only scheme Portway publishes, so the auth panel opens ready to paste a token
            var securitySchemeName = JsonEncodedText.Encode(
                string.IsNullOrWhiteSpace(openApiSettings.SecurityDefinition?.Name) ? "Bearer" : openApiSettings.SecurityDefinition.Name);

            // console-writable values are encoded for the context they land in
            var title = System.Text.Encodings.Web.HtmlEncoder.Default.Encode(openApiSettings.Title);
            var version = Uri.EscapeDataString(openApiSettings.Version);
            string Js(string? value) => JsonSerializer.Serialize(value ?? "");

            // scalar fonts stay off so the console onest files are served from this origin instead
            var customCss = JsonEncodedText.Encode(DocsCss.Replace("{pathBase}", pathBase));

            // Debug logging
            Log.Debug("Scalar configuration: Theme={Theme}, Layout={Layout}",
                openApiSettings.ScalarTheme, openApiSettings.ScalarLayout);

            var configJson = $@"{{
                    ""theme"": ""{GetScalarThemeName(openApiSettings.ScalarTheme)}"",
                    ""layout"": ""{GetScalarLayoutName(openApiSettings.ScalarLayout)}"",
                    ""sidebar"": {sidebarConfig},
                    ""documentDownloadType"": ""{(openApiSettings.ScalarHideDownloadButton ? "none" : "both")}"",
                    ""hideModels"": {(openApiSettings.ScalarHideModels ? "true" : "false")},
                    ""hideClientButton"": {(openApiSettings.ScalarHideClientButton ? "true" : "false")},
                    ""hideTestRequestButton"": {(openApiSettings.ScalarHideTestRequestButton ? "true" : "false")},
                    ""authentication"": {{ ""preferredSecurityScheme"": ""{securitySchemeName}"" }},
                    ""withDefaultFonts"": false,
                    ""customCss"": ""{customCss}"",
                    ""telemetry"": false,
                    ""showDeveloperTools"": ""never"",
                    ""agent"": {{ ""disabled"": true }},
                    ""mcp"": {{ ""disabled"": true }}
                }}";

            string Base64Url(byte[] input)
            {
                var s = Convert.ToBase64String(input);
                return s.TrimEnd('=').Replace('+', '-').Replace('/', '_');
            }

            string RandomBase64UrlId(int minBytes = 8, int maxBytes = 20)
            {
                if (minBytes < 1) minBytes = 1;
                if (maxBytes < minBytes) maxBytes = minBytes;
                int bytes = RandomNumberGenerator.GetInt32(minBytes, maxBytes + 1);
                var b = new byte[bytes];
                RandomNumberGenerator.Fill(b);
                return Base64Url(b);
            }

            string RandomDataAttrName(int rndChars = 8)
            {
                var b = new byte[rndChars];
                RandomNumberGenerator.Fill(b);
                var sb = new StringBuilder(rndChars * 2);
                foreach (var vb in b) sb.Append(vb.ToString("x2"));
                return string.Concat("data-", sb.ToString().AsSpan(0, Math.Min(rndChars, sb.Length)));
            }

            (string id, string attr) GenerateRandomElementIds() =>
                (RandomBase64UrlId(minBytes: 6, maxBytes: 18), RandomDataAttrName(6));

            var (sourceId, sourceAttr) = GenerateRandomElementIds();
            var frontAttr = RandomDataAttrName(6);
            var (asyncId, asyncAttr) = GenerateRandomElementIds();
            var (openapiId, openapiAttr) = GenerateRandomElementIds();
            var (overlayId, overlayAttr) = GenerateRandomElementIds();

            var html = $@"
<!doctype html>
<html>
<head>
    <title>{title}</title>
    <meta charset=""utf-8"" />
    <meta name=""viewport"" content=""width=device-width, initial-scale=1"" />
    <meta name=""referrer"" content=""no-referrer"">
    <link rel=""icon"" href=""favicon.ico"" type=""image/x-icon"">
    <style>
        body {{ margin: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }}
    </style>
</head>
<body>
    <script
        id=""api-reference""
        {frontAttr}=""""
        data-url=""{pathBase}/docs/openapi/{version}/openapi.json""
        data-configuration='{configJson}'
        >
    </script>
    <script
        id=""{sourceId}""
        {sourceAttr}=""""
        >
        (function(){{console.log(atob('JWNAbWVsb3Nzby9wb3J0d2F5JWMuIExpY2Vuc2VkIHVuZGVyICVjQUdQTCAzLjAlYy4='), atob('Y29sb3I6ICM2ZjQyYzE7IGZvbnQtd2VpZ2h0OiBib2xkOyBmb250LXNpemU6IDEycHg7'), atob('Y29sb3I6ICMzMzM7IGZvbnQtc2l6ZTogMTJweDs='), atob('Y29sb3I6ICMyOGE3NDU7IGZvbnQtd2VpZ2h0OiBib2xkOyBmb250LXNpemU6IDEycHg7'), atob('Y29sb3I6ICMzMzM7IGZvbnQtc2l6ZTogMTJ4Ow==') );}})();
    </script>
    <script
        id=""{openapiId}""
        {openapiAttr}=""""
        >
        console.log(
            '%c@melosso/portway%c. OpenAPI URL: %c{pathBase}/docs/openapi/{version}/openapi.json',
            'color: #6f42c1; font-weight: bold; font-size: 12px;',
            'color: #333; font-size: 12px;',
            'color: #dcaf34ff; font-weight: bold; font-size: 12px;'
        );
    </script>
    <script src=""{pathBase}/js/vendor/scalar-api-reference.js""></script>
    <script
        id=""{overlayId}""
        {overlayAttr}=""""
        >
        window.addEventListener('load', function() {{
            // Tooltip
            function createTooltip(text) {{
                const tooltip = document.createElement('div');
                tooltip.textContent = text;
                tooltip.style.cssText = `
                    position: absolute;
                    top: 50%;
                    right: 100%;
                    transform: translateY(-50%) translateX(-5px);
                    background: rgba(0, 0, 0, 0.9);
                    color: white;
                    padding: 4px 8px;
                    border-radius: 4px;
                    font-size: 12px;
                    white-space: nowrap;
                    pointer-events: none;
                    opacity: 0;
                    transition: opacity 0.2s ease, transform 0.2s ease;
                    margin-bottom: 8px;
                    z-index: 10000;
                `;
                return tooltip;
            }}

            // Container for icons
            const iconsContainer = document.createElement('div');
            iconsContainer.style.cssText = `
                position: fixed;
                bottom: 20px;
                right: 20px;
                display: flex;
                gap: 12px;
                z-index: 9999;
            `;

            // GitHub
            const githubContainer = document.createElement('div');
            githubContainer.style.position = 'relative';

            const githubLink = document.createElement('a');
            githubLink.href = 'https://github.com/melosso/portway';
            githubLink.target = '_blank';
            githubLink.innerHTML = `
                <svg viewBox=""0 0 24 24"" width=""20"" height=""20"" style=""fill: #666; opacity: 0.7; transition: opacity 0.2s ease;"">
                    <path d=""M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.30.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z""/>
                </svg>
            `;
            githubLink.style.cssText = `
                background: transparent;
                border: none;
                padding: 0;
                cursor: pointer;
                text-decoration: none;
                display: block;
            `;

            const githubTooltip = createTooltip('View on GitHub');
            githubContainer.appendChild(githubLink);
            githubContainer.appendChild(githubTooltip);

            // License
            const licenseContainer = document.createElement('div');
            licenseContainer.style.position = 'relative';

            const licenseLink = document.createElement('a');
            licenseLink.href = 'https://github.com/melosso/portway/blob/main/LICENSE';
            licenseLink.target = '_blank';
            licenseLink.innerHTML = `
                <svg viewBox=""0 0 24 24"" width=""20"" height=""20"" style=""fill: #666; opacity: 0.7; transition: opacity 0.2s ease;"">
                    <path d=""M12,1L3,5V11C3,16.55 6.84,21.74 12,23C17.16,21.74 21,16.55 21,11V5L12,1M10,17L6,13L7.41,11.59L10,14.17L16.59,7.58L18,9L10,17Z""/>
                </svg>
            `;
            licenseLink.style.cssText = `
                background: transparent;
                border: none;
                padding: 0;
                cursor: pointer;
                text-decoration: none;
                display: block;
            `;

            const licenseTooltip = createTooltip('Licensed under EUPL 1.2');
            licenseContainer.appendChild(licenseLink);
            licenseContainer.appendChild(licenseTooltip);

            // Hover events
            githubContainer.addEventListener('mouseenter', function() {{
                githubLink.querySelector('svg').style.opacity = '1';
                githubTooltip.style.opacity = '1';
                githubTooltip.style.transform = 'translateY(0)';
            }});
            githubContainer.addEventListener('mouseleave', function() {{
                githubLink.querySelector('svg').style.opacity = '0.7';
                githubTooltip.style.opacity = '0';
                githubTooltip.style.transform = 'translateY(5px)';
            }});
            licenseContainer.addEventListener('mouseenter', function() {{
                licenseLink.querySelector('svg').style.opacity = '1';
                licenseTooltip.style.opacity = '1';
                licenseTooltip.style.transform = 'translateY(0)';
            }});
            licenseContainer.addEventListener('mouseleave', function() {{
                licenseLink.querySelector('svg').style.opacity = '0.7';
                licenseTooltip.style.opacity = '0';
                licenseTooltip.style.transform = 'translateY(5px)';
            }});

            {(openApiSettings.Footer.ShowSourceIcon ? "// Conditionally add GitHub icon" : "")}
            {(openApiSettings.Footer.ShowSourceIcon ? "iconsContainer.appendChild(githubContainer);" : "")}

            iconsContainer.appendChild(licenseContainer);
            document.body.appendChild(iconsContainer);
        }});
    </script>
    <script
        id=""{asyncId}""
        {asyncAttr}=""""
        >
        const observer = new MutationObserver(() => {{
            const link = document.querySelector('a[href^=""https://scalar.com/?utm_source=powered-by""]');
            if (link) {{
                link.textContent = {Js(openApiSettings.Footer.Text)};
                link.href = {Js(PortwayApi.Services.Configuration.SettingsWriteService.IsSafeLink(openApiSettings.Footer.Url) ? openApiSettings.Footer.Url : "#")};
                link.target = {Js(openApiSettings.Footer.Target)};
                observer.disconnect();
            }}
        }});
        observer.observe(document.body, {{ childList: true, subtree: true }});
    </script>
</body>
</html>";
            return Results.Content(html, "text/html");
        });

        Log.Information("OpenAPI documentation is enabled and available at '/docs'.");
    }

    // To-do: drop the scalar 1.72.4 nested tag workarounds once upstream handles parent tags
    private const string DocsCss = """
        @font-face { font-family: "Onest"; font-weight: 400 700; font-display: swap; src: url("{pathBase}/fonts/onest-latin-ext.woff2") format("woff2"); unicode-range: U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF; }
        @font-face { font-family: "Onest"; font-weight: 400 700; font-display: swap; src: url("{pathBase}/fonts/onest-latin.woff2") format("woff2"); unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD; }
        :root, .light-mode, .dark-mode { --scalar-font: "Onest", ui-sans-serif, system-ui, sans-serif; }
        .scalar-app nav.context-bar { display: none; }
        .scalar-app .endpoints-card:not(:has(li)) { display: none; }
        """;

    private static string GetScalarThemeName(string theme)
    {
        return theme?.ToLowerInvariant() switch
        {
            "alternate" => "alternate",
            "default" => "default",
            "moon" => "moon",
            "purple" => "purple",
            "solarized" => "solarized",
            "blueplanet" => "bluePlanet",
            "saturn" => "saturn",
            "kepler" => "kepler",
            "mars" => "mars",
            "deepspace" => "deepSpace",
            "elysiajs" => "elysiajs",
            "fastify" => "fastify",
            "laserwave" => "laserwave",
            "none" => "none",
            _ => "purple"
        };
    }

    private static string GetScalarLayoutName(string layout)
    {
        return layout?.ToLowerInvariant() switch
        {
            "modern" => "modern",
            "classic" => "classic",
            _ => "modern"
        };
    }

    // Helper method for safely parsing enums with fallback
    public static T ParseEnum<T>(string value, T defaultValue) where T : struct, Enum
    {
        if (string.IsNullOrWhiteSpace(value) || !Enum.TryParse<T>(value, true, out var result))
        {
            return defaultValue;
        }
        return result;
    }
}
